package com.webstore.entity;
// Generated 27-Nov-2020, 6:52:12 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@NamedQueries({
	@NamedQuery(name="Category.findAll", query= "SELECT c FROM Category c ORDER BY c.name"),
	@NamedQuery(name="Category.countAll", query= "SELECT count(*) FROM Category c"),
	@NamedQuery(name="Category.findByName",query="SELECT c FROM Category c WHERE c.name=:name")
})
@Table(name = "category", catalog = "webstoredb")
public class Category implements java.io.Serializable {

	private int categoryId;
	private String name;
	private Set<Item> items = new HashSet<Item>(0);

	public Category() {
	}

	public Category(int categoryId, String name) {
		this.categoryId = categoryId;
		this.name = name;
	}
	
	public Category(String name) {
		this.name = name;
	}

	public Category(int categoryId, String name, Set<Item> items) {
		this.categoryId = categoryId;
		this.name = name;
		this.items = items;
	}

	
	@Column(name = "category_id", unique = true, nullable = false)
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

}
